name: meetmax
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.1.0
  http: ^0.13.5              # For HTTP response simulation
  intl: ^0.18.1              # For date formatting
  shared_preferences: ^2.2.2 # For persistent storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  provider: ^6.0.5           # For dependency injection
  uuid: ^3.0.7               # For ID generation

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6       # For code generation if needed
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
